<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;shipping;governorate</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\IApplicationDbContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Negin.IdentityServer.Api\appsettings.Development.json" Link="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Negin.IdentityServer.Api\appsettings.json" Link="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="13.0.1" />
	<PackageReference Include="HigginsSoft.IdentityServer8" Version="8.0.4" />
	<PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
	<PackageReference Include="HigginsSoft.IdentityServer8.AspNetIdentity" Version="8.0.4" />
	<PackageReference Include="HigginsSoft.IdentityServer8.EntityFramework" Version="8.0.4" />
	<PackageReference Include="HigginsSoft.IdentityServer8.EntityFramework.Storage" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Negin.IdentityServer.Application\IdentityServer.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Nsp.Common">
      <HintPath>..\Library\Nsp.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
